### PR TITLE
OpenSSL added to ubuntu image

### PR DESCRIPTION
**Pull request by ArnisLielturks**

### CODE REVIEW

**Comment by ArnisLielturks** [comment]
This is the first step to enable URHO3D_SSL=1 option to some of the CI builds

**Comment by weitjong** [comment]
I wonder you are actually intended to add this new dev package for the [native Dockerfile](https://github.com/weitjong/dockerized/blob/master/urho3d/native/Dockerfile) instead. Adding it to the MinGW host should make no differences to the MinGW cross-compiler when targeting Windows.

**Comment by ArnisLielturks** [comment]
Ah, you're right. Since the change is so small, can you add the one package yourself tot the native docker file? I'm closing this PR then.

**Comment by weitjong** [comment]
It is done. The DBE images should be ready in a few minutes. You can use them in the CI job for your dev branch by including `DBE_TAG=latest` as one of the environment variable. When your dev branch is ready to be merged, give me a head up first so that I can retag those DBE images with "master" tag.

**Comment by ArnisLielturks** [comment]
Nice, thank you!

**Pull request closed without merging**
